const shared = {
  email: 'azizkza99@gmail.com',
  phone: '+966 54 994 9023',
  phoneHref: 'tel:+966549949023',
  linkedin: 'https://www.linkedin.com/in/abdelazizabuthuraya',
  github: 'https://github.com/azizkza99',
  portfolio: 'https://cv-ruby-two.vercel.app',
  projects: [
    {
      id: 'form',
      repo: 'https://github.com/azizkza99/bezi-product-viewer',
      live: 'https://bezi-product-viewer.vercel.app',
      stack: ['React', 'JavaScript', 'Three.js', 'WebGL'],
    },
    {
      id: 'kayan',
      repo: 'https://github.com/azizkza99/kayan-app',
      live: 'https://kayan-app-henna.vercel.app',
      stack: ['React', 'TypeScript', 'Supabase', 'PostgreSQL'],
    },
    {
      id: 'eclipse',
      live: 'https://eclipse-luxury-experience.vercel.app',
      stack: ['TanStack Start', 'React', 'TypeScript', 'Resend'],
    },
    {
      id: 'aether',
      repo: 'https://github.com/azizkza99/aether-os',
      live: 'https://aether-os-seven-kappa.vercel.app',
      stack: ['React', 'JavaScript', 'Canvas', 'Web Audio'],
    },
    {
      id: 'afoq',
      repo: 'https://github.com/azizkza99/afoq-landing-page',
      live: 'https://afoq-landing-page.vercel.app',
      stack: ['React', 'JavaScript', 'Tailwind CSS', 'Vite'],
    },
    {
      id: 'nexus',
      repo: 'https://github.com/azizkza99/nexus-ai-template',
      live: 'https://nexus-ai-rho-two.vercel.app',
      stack: ['React', 'JavaScript', 'Tailwind CSS', 'Vite'],
    },
  ],
}

export const content = {
  en: {
    meta: {
      title: 'Abdelaziz Abuthuraya | Industrial Engineer & Digital Systems Builder',
      description: 'Industrial Engineer in Jeddah with hands-on experience in production planning, process improvement, quality, supply chain, EPC coordination, and practical digital systems.',
    },
    skip: 'Skip to content',
    navigationLabel: 'Main navigation',
    name: 'Abdelaziz Abuthuraya',
    brandRole: 'Industrial Engineering · Operations · Digital Systems',
    role: 'Industrial engineer connecting operations, data, and practical digital systems.',
    location: 'Jeddah, Saudi Arabia',
    availability: 'Based in Jeddah • Open to opportunities across Saudi Arabia',
    eyebrow: 'Production planning • Process improvement • Industrial digitalization',
    intro: 'I bring hands-on manufacturing and EPC experience together with analytical problem-solving and deployed bilingual software to make workflows, products, and decisions clearer.',
    contact: 'Start a conversation',
    download: 'Download English CV',
    cvShort: 'CV',
    downloadHref: '/resumes/Abdelaziz-Abuthuraya-CV-EN.pdf',
    language: 'العربية',
    languageLabel: 'Switch to Arabic',
    dashboardLabel: 'Professional profile summary',
    status: 'Open to opportunities',
    dashboardText: 'Engineering judgment, operational context, and digital execution in one profile.',
    dashboardItems: ['Production', 'Operations', 'Analytics', 'Systems'],
    nav: ['Profile', 'Experience', 'Projects', 'Skills', 'Education'],
    navIds: ['about', 'experience', 'projects', 'skills', 'education'],
    sections: {
      about: 'An engineering profile built across factory floors and digital products',
      experience: 'Hands-on experience across Saudi Arabia and Türkiye',
      projects: 'Deployed systems, not static mockups',
      skills: 'Engineering and technical capabilities',
      education: 'Education and analytical case studies',
    },
    sectionEyebrows: {
      about: 'Professional profile',
      experience: 'Experience',
      projects: 'Selected work',
      skills: 'Toolkit',
      education: 'Academic foundation',
    },
    summary: 'Industrial Engineering graduate with approximately 14 months of internship experience across production planning, manufacturing operations, quality inspection, process improvement, supply-chain analysis, and EPC coordination. I complement that foundation by building bilingual digital systems with React, TypeScript, Supabase, and Three.js.',
    focus: [
      { title: 'Production planning', text: 'Daily schedules, workflow priorities, cross-functional coordination, and delivery alignment.' },
      { title: 'Process improvement', text: 'Bottleneck identification, waste awareness, material flow, and data-backed recommendations.' },
      { title: 'Quality & operations', text: 'Surface and dimensional inspection with practical exposure to multi-stage manufacturing.' },
      { title: 'Digital systems', text: 'Bilingual interfaces that turn specifications, workflows, and customer inputs into usable tools.' },
    ],
    signals: [
      { value: '14', label: 'Months of practical experience' },
      { value: '2', label: 'Countries' },
      { value: '6', label: 'Deployed digital projects' },
      { value: '3', label: 'Languages' },
    ],
    experience: [
      {
        role: 'Production Planning Intern',
        company: 'Edaş Yatak',
        place: 'Kayseri, Türkiye',
        date: 'Aug – Oct 2025',
        bullets: [
          'Prepared and monitored daily production schedules to keep workflow priorities aligned with delivery dates.',
          'Coordinated across production and support departments to surface scheduling conflicts and reduce avoidable delays.',
          'Reviewed production-performance data to identify bottlenecks and propose practical workflow improvements.',
        ],
      },
      {
        role: 'Operations & Process Improvement Intern',
        company: 'Murat Şahin Orman Ürünleri',
        place: 'Tokat, Türkiye',
        date: 'Jan – Jul 2025',
        bullets: [
          'Supported plywood and MDF operations across cutting, pressing, finishing, packaging, and finished-goods handling.',
          'Monitored output, material movement, storage, and workflow constraints to identify waste-reduction opportunities.',
          'Performed surface and dimensional quality checks and used SolidWorks for basic engineering-support tasks.',
        ],
      },
      {
        role: 'Project Management Intern',
        company: 'Delta CJSC',
        place: 'Jeddah, Saudi Arabia',
        date: 'Jul – Aug 2024',
        bullets: [
          'Supported daily EPC coordination and organized project documentation for clearer task and information follow-up.',
          'Maintained Excel trackers and prepared scheduling and logistics reports for project-support activities.',
          'Contributed workflow-improvement ideas during coordination meetings in a hybrid work environment.',
        ],
      },
      {
        role: 'Engineering Intern',
        company: 'Delta CJSC',
        place: 'Riyadh, Saudi Arabia',
        date: 'Jul – Aug 2022',
        bullets: [
          'Supported coordination across engineering, procurement, and construction activities.',
          'Monitored timelines and project KPIs to help follow milestones and schedule deviations.',
          'Prepared Excel-based logistics and scheduling reports to improve data visibility and decision support.',
        ],
      },
    ],
    projectsIntro: 'Six live projects demonstrate product visualization, secure data capture, bilingual UX, interface systems, and front-end engineering. Each scope is described exactly as implemented.',
    projectCopy: {
      form: {
        type: 'Industrial product visualization',
        title: 'FORM — Interactive 3D Door Configurator',
        description: 'A bilingual configurator for dimensions, finishes, hardware, hinge direction, and opening angle, with a procedural Three.js model, live specification summary, exploded view, and WebGL fallback.',
      },
      kayan: {
        type: 'Workflow automation interface',
        title: 'Kayan — Workflow Discovery & Inquiry System',
        description: 'An Arabic/English React interface with a working Supabase/PostgreSQL inquiry flow, localized validation, submission feedback, and Row Level Security policies.',
      },
      eclipse: {
        type: 'Full-stack hospitality experience',
        title: 'ECLIPSE — Specialty Coffee Experience',
        description: 'A bilingual TanStack Start experience with guided coffee discovery, server-side validation, consent and anti-spam controls, and Resend email integration.',
      },
      aether: {
        type: 'Interactive systems experiment',
        title: 'Aether OS — Browser Desktop Environment',
        description: 'A browser-based desktop experiment with window management, a command-driven terminal, an in-memory file system, Canvas visuals, and Web Audio interactions.',
      },
      afoq: {
        type: 'Bilingual creative platform',
        title: 'AFOQ — Arabic-First Studio Experience',
        description: 'A responsive Arabic-first creative-studio concept with bilingual content architecture, optimized media presentation, structured service discovery, and polished interaction design.',
      },
      nexus: {
        type: 'SaaS interface concept',
        title: 'Nexus AI — Product Planning Workspace',
        description: 'A bilingual browser-based SaaS concept for structuring product ideas and workflows, built as a responsive front-end prototype with clear information hierarchy and interaction states.',
      },
    },
    visit: 'Live demo',
    source: 'Source code',
    skillGroups: [
      {
        title: 'Industrial Engineering & Operations',
        items: ['Production planning', 'Process improvement', 'Operations research', 'Lean Manufacturing', '5S', 'Quality control', 'Supply chain analysis', 'Project coordination'],
      },
      {
        title: 'Analytics & Engineering Tools',
        items: ['Microsoft Excel', 'Data analysis', 'Mathematical modelling', 'Deterministic optimization', 'Mixed-Integer Programming', 'SolidWorks', 'AutoCAD fundamentals'],
      },
      {
        title: 'Digital Systems',
        items: ['React', 'TypeScript', 'JavaScript', 'TanStack Start', 'Supabase', 'PostgreSQL', 'REST APIs', 'Three.js', 'WebGL', 'Git / GitHub', 'Vercel'],
      },
      {
        title: 'Languages',
        items: ['Arabic — Native', 'English — C1', 'Turkish — B1'],
      },
    ],
    education: [
      {
        degree: 'BSc in Industrial Engineering',
        school: 'Üsküdar University',
        place: 'Istanbul, Türkiye',
        date: '2020 – 2024',
        detail: 'GPA: 2.75 / 4.00 · Language of instruction: English',
      },
      {
        degree: 'Graduate Coursework in Industrial Engineering',
        school: 'Abdullah Gül University',
        place: 'Kayseri, Türkiye',
        date: 'Jan – May 2026',
        detail: 'One semester: Supply Chain Management, Marketing Management, and Mathematical Modeling · No degree awarded',
      },
    ],
    academic: [
      {
        title: 'Integrated Supply Chain & Revenue Analysis',
        description: 'Analyzed raw-material procurement, production performance, revenue trends, 85% machine utilization, and waste rates of 0.5–1.5% to identify operational improvement opportunities.',
      },
      {
        title: 'Virtual Machine Placement under QoS Constraints',
        description: 'Developed a QoS- and SLA-constrained Mixed-Integer Programming model and achieved a zero optimality gap across the tested demand scenarios.',
      },
      {
        title: 'Human Resources Planning & Employee Selection',
        description: 'Designed and analyzed a 14-question survey across eight companies covering workforce planning, selection, development, and succession planning.',
      },
    ],
    footerKicker: 'Operations become stronger when information becomes clearer',
    footer: 'Open to industrial engineering, production planning, operations, process improvement, quality, supply chain, and industrial digitalization roles.',
    phoneLabel: 'Phone',
  },

  ar: {
    meta: {
      title: 'عبد العزيز أبو ثريا | مهندس صناعي ومطور أنظمة رقمية',
      description: 'مهندس صناعي في جدة بخبرة عملية في تخطيط الإنتاج وتحسين العمليات والجودة وسلاسل الإمداد وتنسيق مشاريع EPC وتطوير الأنظمة الرقمية.',
    },
    skip: 'انتقل إلى المحتوى',
    navigationLabel: 'التنقل الرئيسي',
    name: 'عبد العزيز أبو ثريا',
    brandRole: 'الهندسة الصناعية · العمليات · الأنظمة الرقمية',
    role: 'مهندس صناعي يربط العمليات والبيانات بالأنظمة الرقمية العملية.',
    location: 'جدة، المملكة العربية السعودية',
    availability: 'مقيم في جدة • متاح للفرص في مختلف مناطق المملكة',
    eyebrow: 'تخطيط الإنتاج • تحسين العمليات • الرقمنة الصناعية',
    intro: 'أجمع بين الخبرة الميدانية في التصنيع ومشاريع EPC والتحليل الهندسي وتطوير برمجيات ثنائية اللغة لجعل سير العمل والمنتجات والقرارات أكثر وضوحًا.',
    contact: 'ابدأ محادثة',
    download: 'تحميل السيرة العربية',
    cvShort: 'CV',
    downloadHref: '/resumes/Abdelaziz-Abuthuraya-CV-AR.pdf',
    language: 'English',
    languageLabel: 'Switch to English',
    dashboardLabel: 'ملخص الملف المهني',
    status: 'متاح للفرص',
    dashboardText: 'حكم هندسي وسياق تشغيلي وتنفيذ رقمي في ملف مهني واحد.',
    dashboardItems: ['الإنتاج', 'العمليات', 'التحليل', 'الأنظمة'],
    nav: ['نبذة', 'الخبرة', 'المشاريع', 'المهارات', 'التعليم'],
    navIds: ['about', 'experience', 'projects', 'skills', 'education'],
    sections: {
      about: 'ملف هندسي بُني بين أرض المصنع والمنتجات الرقمية',
      experience: 'خبرة ميدانية عبر السعودية وتركيا',
      projects: 'أنظمة منشورة وليست مجرد تصاميم ثابتة',
      skills: 'قدرات هندسية وتقنية',
      education: 'التعليم ودراسات الحالة التحليلية',
    },
    sectionEyebrows: {
      about: 'الملف المهني',
      experience: 'الخبرة',
      projects: 'أعمال مختارة',
      skills: 'مجموعة الأدوات',
      education: 'الأساس الأكاديمي',
    },
    summary: 'خريج هندسة صناعية بخبرة تدريبية تقارب 14 شهرًا في تخطيط الإنتاج وعمليات التصنيع وفحص الجودة وتحسين العمليات وتحليل سلاسل الإمداد وتنسيق مشاريع EPC. أدعم هذا الأساس ببناء أنظمة رقمية ثنائية اللغة باستخدام React وTypeScript وSupabase وThree.js.',
    focus: [
      { title: 'تخطيط الإنتاج', text: 'الجداول اليومية وأولويات سير العمل والتنسيق بين الأقسام والالتزام بمواعيد التسليم.' },
      { title: 'تحسين العمليات', text: 'تحديد الاختناقات والهدر وتدفق المواد وصياغة توصيات مدعومة بالبيانات.' },
      { title: 'الجودة والعمليات', text: 'فحوصات سطحية وبُعدية وخبرة عملية في مراحل تصنيع متعددة.' },
      { title: 'الأنظمة الرقمية', text: 'واجهات ثنائية اللغة تحوّل المواصفات وسير العمل ومدخلات العملاء إلى أدوات عملية.' },
    ],
    signals: [
      { value: '14', label: 'شهرًا من الخبرة العملية' },
      { value: '2', label: 'دول' },
      { value: '6', label: 'مشاريع رقمية منشورة' },
      { value: '3', label: 'لغات' },
    ],
    experience: [
      {
        role: 'متدرب تخطيط إنتاج',
        company: 'Edaş Yatak',
        place: 'قيصري، تركيا',
        date: 'أغسطس – أكتوبر 2025',
        bullets: [
          'أعددت وتابعت جداول الإنتاج اليومية لربط أولويات سير العمل بمواعيد التسليم.',
          'نسّقت بين أقسام الإنتاج والدعم لإظهار تعارضات الجدولة وتقليل التأخيرات الممكن تجنبها.',
          'راجعت بيانات أداء الإنتاج لتحديد الاختناقات واقتراح تحسينات عملية لسير العمل.',
        ],
      },
      {
        role: 'متدرب عمليات وتحسين إجراءات',
        company: 'Murat Şahin Orman Ürünleri',
        place: 'توكات، تركيا',
        date: 'يناير – يوليو 2025',
        bullets: [
          'دعمت عمليات إنتاج ألواح Plywood وMDF عبر مراحل القطع والكبس والتشطيب والتعبئة ومناولة المنتجات الجاهزة.',
          'راقبت الإنتاج وحركة المواد والتخزين وقيود سير العمل لتحديد فرص تقليل الهدر.',
          'أجريت فحوصات جودة سطحية وبُعدية واستخدمت SolidWorks في مهام الدعم الهندسي الأساسية.',
        ],
      },
      {
        role: 'متدرب إدارة مشاريع',
        company: 'Delta CJSC',
        place: 'جدة، السعودية',
        date: 'يوليو – أغسطس 2024',
        bullets: [
          'دعمت تنسيق مشاريع EPC اليومية ونظّمت وثائق المشروع لتسهيل متابعة المعلومات والمهام.',
          'حدّثت سجلات Excel وأعددت تقارير الجدولة والخدمات اللوجستية.',
          'ساهمت بأفكار لتحسين سير العمل خلال اجتماعات التنسيق في بيئة عمل هجينة.',
        ],
      },
      {
        role: 'متدرب هندسي',
        company: 'Delta CJSC',
        place: 'الرياض، السعودية',
        date: 'يوليو – أغسطس 2022',
        bullets: [
          'دعمت التنسيق بين أنشطة الهندسة والمشتريات والإنشاءات.',
          'تابعت الجداول الزمنية ومؤشرات الأداء الرئيسية لرصد المعالم والانحرافات الزمنية.',
          'أعددت تقارير Excel للجدولة والخدمات اللوجستية بهدف تحسين وضوح البيانات ودعم القرار.',
        ],
      },
    ],
    projectsIntro: 'ستة مشاريع حية تبرهن على مهارات عرض المنتجات وجمع البيانات الآمن وتجربة المستخدم ثنائية اللغة وبناء الواجهات. وُصف نطاق كل مشروع كما نُفذ فعليًا.',
    projectCopy: {
      form: {
        type: 'عرض منتجات صناعية ثلاثي الأبعاد',
        title: 'FORM — أداة تفاعلية ثلاثية الأبعاد لتخصيص الأبواب',
        description: 'أداة ثنائية اللغة لتعديل الأبعاد والتشطيبات والملحقات واتجاه المفصلات وزاوية الفتح، مع نموذج Three.js إجرائي وملخص مواصفات مباشر وعرض تفصيلي للمكونات ووضع بديل لـWebGL.',
      },
      kayan: {
        type: 'واجهة لأتمتة سير العمل',
        title: 'Kayan — نظام لاكتشاف سير العمل والاستفسارات',
        description: 'واجهة عربية وإنجليزية مبنية بـReact تتضمن نموذج استفسار فعليًا على Supabase/PostgreSQL وتحققًا محليًا ورسائل استجابة وسياسات أمان على مستوى الصفوف.',
      },
      eclipse: {
        type: 'تجربة ضيافة متكاملة',
        title: 'ECLIPSE — تجربة للقهوة المختصة',
        description: 'تجربة ثنائية اللغة مبنية بـTanStack Start تشمل اكتشافًا موجهًا للقهوة وتحققًا من جهة الخادم وضوابط موافقة ومكافحة الرسائل المزعجة وتكاملًا مع Resend.',
      },
      aether: {
        type: 'تجربة تفاعلية للأنظمة',
        title: 'Aether OS — بيئة سطح مكتب داخل المتصفح',
        description: 'تجربة سطح مكتب تعمل في المتصفح وتتضمن إدارة النوافذ ووحدة طرفية بالأوامر ونظام ملفات في الذاكرة ورسومات Canvas وتفاعلات Web Audio.',
      },
      afoq: {
        type: 'منصة إبداعية ثنائية اللغة',
        title: 'AFOQ — تجربة استوديو عربية أولًا',
        description: 'مفهوم متجاوب لاستوديو إبداعي عربي أولًا مع بنية محتوى ثنائية اللغة وعرض وسائط محسّن واستكشاف منظم للخدمات وتصميم تفاعلي مصقول.',
      },
      nexus: {
        type: 'مفهوم واجهة SaaS',
        title: 'Nexus AI — مساحة لتخطيط المنتجات',
        description: 'مفهوم SaaS ثنائي اللغة يعمل داخل المتصفح لتنظيم أفكار المنتجات وسير العمل، بُني كنموذج واجهة أمامية متجاوب بهيكل معلومات وحالات تفاعل واضحة.',
      },
    },
    visit: 'المعاينة الحية',
    source: 'الكود المصدري',
    skillGroups: [
      {
        title: 'الهندسة الصناعية والعمليات',
        items: ['تخطيط الإنتاج', 'تحسين العمليات', 'بحوث العمليات', 'التصنيع الرشيق', '5S', 'ضبط الجودة', 'تحليل سلاسل الإمداد', 'تنسيق المشاريع'],
      },
      {
        title: 'التحليل والأدوات الهندسية',
        items: ['Microsoft Excel', 'تحليل البيانات', 'النمذجة الرياضية', 'التحسين المحدد', 'البرمجة الخطية الصحيحة المختلطة', 'SolidWorks', 'أساسيات AutoCAD'],
      },
      {
        title: 'الأنظمة الرقمية',
        items: ['React', 'TypeScript', 'JavaScript', 'TanStack Start', 'Supabase', 'PostgreSQL', 'REST APIs', 'Three.js', 'WebGL', 'Git / GitHub', 'Vercel'],
      },
      {
        title: 'اللغات',
        items: ['العربية — اللغة الأم', 'الإنجليزية — C1', 'التركية — B1'],
      },
    ],
    education: [
      {
        degree: 'بكالوريوس الهندسة الصناعية',
        school: 'Üsküdar University',
        place: 'إسطنبول، تركيا',
        date: '2020 – 2024',
        detail: 'المعدل: 2.75 / 4.00 · لغة الدراسة: الإنجليزية',
      },
      {
        degree: 'مقررات دراسات عليا في الهندسة الصناعية',
        school: 'Abdullah Gül University',
        place: 'قيصري، تركيا',
        date: 'يناير – مايو 2026',
        detail: 'فصل دراسي واحد: إدارة سلاسل الإمداد وإدارة التسويق والنمذجة الرياضية · لم تُمنح درجة علمية',
      },
    ],
    academic: [
      {
        title: 'تحليل متكامل لسلسلة الإمداد والإيرادات',
        description: 'حللت مشتريات المواد الخام وأداء الإنتاج واتجاهات الإيرادات واستغلال الآلات بنسبة 85% ومعدلات الهدر بين 0.5% و1.5% لتحديد فرص التحسين التشغيلي.',
      },
      {
        title: 'توزيع الآلات الافتراضية ضمن قيود جودة الخدمة',
        description: 'طورت نموذج برمجة خطية صحيحة مختلطة ضمن قيود QoS وSLA وحقق فجوة مثالية قدرها صفر في سيناريوهات الطلب المختبرة.',
      },
      {
        title: 'تخطيط الموارد البشرية واختيار الموظفين',
        description: 'صممت وحللت استبيانًا من 14 سؤالًا عبر 8 شركات لدراسة تخطيط القوى العاملة والاختيار والتطوير والتعاقب الوظيفي.',
      },
    ],
    footerKicker: 'تصبح العمليات أقوى عندما تصبح المعلومات أوضح',
    footer: 'متاح لفرص الهندسة الصناعية وتخطيط الإنتاج والعمليات وتحسين الإجراءات والجودة وسلاسل الإمداد والرقمنة الصناعية.',
    phoneLabel: 'الهاتف',
  },
}

export { shared }
