const shared = {
  email: 'azizkza99@gmail.com',
  linkedin: 'https://www.linkedin.com/in/abdelazizabuthuraya',
  github: 'https://github.com/azizkza99',
  projects: [
    { id: 'form', repo: 'https://github.com/azizkza99/bezi-product-viewer', live: 'https://bezi-product-viewer.vercel.app', stack: ['React', 'Three.js', 'Vite', 'WebGL'] },
    { id: 'kayan', repo: 'https://github.com/azizkza99/kayan-app', live: 'https://kayan-app-henna.vercel.app', stack: ['React', 'TypeScript', 'Supabase', 'PostgreSQL'] },
    { id: 'eclipse', live: 'https://eclipse-luxury-experience.vercel.app', stack: ['TanStack Start', 'React', 'TypeScript', 'Resend'] },
  ],
}

export const content = {
  ar: {
    meta: {
      title: 'عبد العزيز أبو ثريا | مهندس صناعي وحلول رقمية',
      description: 'مهندس صناعي في جدة بخبرة في تخطيط الإنتاج وتحسين العمليات والجودة، مع مهارات عملية في تطوير الحلول الرقمية.',
    },
    skip: 'انتقل إلى المحتوى',
    navigationLabel: 'التنقل الرئيسي',
    name: 'عبد العزيز أبو ثريا',
    brandRole: 'هندسة صناعية × حلول رقمية',
    role: 'مهندس صناعي يبني عمليات أفضل وأدوات رقمية أوضح.',
    location: 'جدة، المملكة العربية السعودية',
    availability: 'مقيم في السعودية • إقامة سارية • متاح للانتقال',
    eyebrow: 'تخطيط الإنتاج • تحسين العمليات • التحول الرقمي',
    intro: 'أجمع بين الخبرة الميدانية في التصنيع والتفكير التحليلي وتطوير الويب لتحويل تحديات التشغيل إلى حلول عملية قابلة للقياس والاستخدام.',
    contact: 'تواصل معي',
    download: 'تحميل السيرة',
    cvShort: 'CV',
    downloadHref: '/resumes/Abdelaziz-Abuthuraya-CV-AR.pdf',
    language: 'English',
    languageLabel: 'Switch to English',
    dashboardLabel: 'ملخص الملف المهني',
    status: 'متاح للفرص',
    dashboardText: 'نقطة التقاء العمليات والبيانات والتجارب الرقمية.',
    dashboardItems: ['الإنتاج', 'العمليات', 'البيانات', 'الأنظمة'],
    nav: ['نبذة', 'الخبرة', 'المشاريع', 'المهارات', 'التعليم'],
    navIds: ['about', 'experience', 'projects', 'skills', 'education'],
    sections: { about: 'قيمة هندسية متعددة التخصصات', experience: 'خبرة ميدانية عبر السعودية وتركيا', projects: 'حلول رقمية مبنية للتطبيق', skills: 'قدرات هندسية وتقنية', education: 'التعليم والمشاريع الأكاديمية' },
    sectionEyebrows: { about: 'الملف المهني', experience: 'الخبرة', projects: 'المشاريع التقنية', skills: 'مجموعة الأدوات', education: 'الأساس الأكاديمي' },
    summary: 'خريج هندسة صناعية بخبرة تدريبية في التصنيع ومشاريع EPC في تركيا والسعودية. أمتلك خلفية عملية في تخطيط الإنتاج وضبط الجودة وتحسين العمليات وتحليل سلاسل الإمداد، وأدعمها بمهارات تطوير الويب باستخدام React وTypeScript وSupabase وThree.js.',
    focus: [
      { title: 'تخطيط الإنتاج', text: 'متابعة الجداول اليومية وربط أولويات العمل بمواعيد التسليم.' },
      { title: 'تحسين العمليات', text: 'رصد الاختناقات والهدر وتحويل البيانات إلى مقترحات واضحة.' },
      { title: 'الجودة والتدفق', text: 'فحوصات سطحية وبُعدية وفهم عملي لحركة المواد داخل المصنع.' },
      { title: 'الحلول الرقمية', text: 'واجهات ثنائية اللغة تربط البيانات والعمليات بتجربة استخدام عملية.' },
    ],
    signals: [{ value: '4', label: 'خبرات ميدانية' }, { value: '2', label: 'دول' }, { value: '3', label: 'مشاريع تقنية' }, { value: '3', label: 'لغات' }],
    experience: [
      { role: 'متدرب تخطيط إنتاج', company: 'EDAS Yatak', place: 'قيصري، تركيا', date: 'أغسطس - أكتوبر 2025', bullets: ['المساعدة في إعداد ومتابعة جداول الإنتاج اليومية لمواءمة أنشطة الإنتاج مع مواعيد التسليم.', 'التنسيق مع الأقسام المختلفة لدعم تدفق الإنتاج ومعالجة تأخيرات الجدولة.', 'تحليل بيانات أداء الإنتاج لتحديد الاختناقات والتوصية بتحسينات على العمليات.'] },
      { role: 'متدرب عمليات وتحسين عمليات', company: 'Murat Şahin Orman Ürünleri', place: 'توكات، تركيا', date: 'يناير - يوليو 2025', bullets: ['دعم أنشطة إنتاج ألواح Plywood وMDF عبر مراحل القطع والكبس وتشطيب الأسطح.', 'مراقبة سير الإنتاج لتحديد فرص تقليل الهدر وتحسين مناولة المواد.', 'متابعة الإنتاج اليومي والتعبئة والتخزين، وتنفيذ فحوصات جودة سطحية وبُعدية، واستخدام SolidWorks في مهام دعم هندسي أساسية.'] },
      { role: 'متدرب إدارة مشاريع', company: 'Delta CJSC', place: 'جدة، السعودية', date: 'يوليو - أغسطس 2024', bullets: ['دعم التنسيق اليومي ضمن فريق الهندسة والمشتريات والإنشاءات (EPC) وتنظيم وثائق المشروع.', 'تحديث سجلات Excel وإعداد تقارير لدعم اللوجستيات وجدولة المشروع.', 'المشاركة في اجتماعات الفريق وتقديم مقترحات لتحسين كفاءة سير العمل.'] },
      { role: 'متدرب هندسي', company: 'Delta CJSC', place: 'الرياض، السعودية', date: 'يوليو - أغسطس 2022', bullets: ['دعم التنسيق بين أنشطة الهندسة والمشتريات والإنشاءات.', 'متابعة الجداول الزمنية ومؤشرات الأداء الرئيسية لدعم رصد مراحل المشروع.', 'إعداد وتحديث تقارير Excel لدعم الجدولة والتنسيق اللوجستي.'] },
    ],
    projectsIntro: 'ثلاثة نماذج عملية توضّح كيف أستخدم البرمجة لحل مشكلات العرض والتواصل وجمع البيانات.',
    projectCopy: {
      form: { type: 'تصور منتجات ثلاثي الأبعاد', title: 'FORM — أداة تهيئة أبواب تفاعلية', description: 'أداة ثنائية اللغة تتيح تعديل الأبعاد والتشطيبات واتجاه المفصلات وزاوية الفتح، مع ملخص مواصفات مباشر وعرض تفصيلي للمكونات.' },
      kayan: { type: 'واجهة أتمتة سير العمل', title: 'Kayan — مفهوم لعمليات أكثر وضوحًا', description: 'واجهة عربية وإنجليزية مبنية بـReact وTypeScript، مع نموذج استفسار فعلي على Supabase/PostgreSQL، والتحقق من المدخلات وسياسات Row Level Security.' },
      eclipse: { type: 'تجربة ويب للضيافة', title: 'ECLIPSE — موقع قهوة مختصة', description: 'تجربة ثنائية اللغة مبنية بـTanStack Start، تشمل اكتشافًا موجّهًا للقهوة ونموذج اهتمام متحققًا منه على الخادم ومتصلًا بخدمة Resend.' },
    },
    visit: 'المعاينة الحية',
    source: 'الكود',
    skillGroups: [
      { title: 'الهندسة والعمليات', items: ['تخطيط الإنتاج', 'تحسين العمليات', 'Lean Manufacturing', '5S', 'ضبط الجودة', 'سلاسل الإمداد', 'النمذجة الرياضية', 'تحليل البيانات'] },
      { title: 'التطوير والأنظمة', items: ['React', 'TypeScript', 'JavaScript', 'TanStack Start', 'Supabase', 'PostgreSQL', 'REST APIs', 'Three.js', 'WebGL', 'Git / GitHub', 'Vercel'] },
      { title: 'الأدوات واللغات', items: ['Microsoft Excel', 'SolidWorks', 'AutoCAD', 'العربية — اللغة الأم', 'الإنجليزية — C1', 'التركية — B1'] },
    ],
    education: { degree: 'بكالوريوس الهندسة الصناعية', school: 'Üsküdar University', place: 'إسطنبول، تركيا', date: '2020 - 2024', detail: 'لغة الدراسة: الإنجليزية' },
    academic: [
      { title: 'سلسلة الإمداد وتحليل الإيرادات', description: 'تحليل شراء المواد الخام وأداء الإنتاج واتجاهات الإيرادات، مع تقييم استخدام الآلات بنسبة 85% ومعدلات هدر بين 0.5% و1.5% لتحديد فرص التحسين.' },
      { title: 'توزيع الأجهزة الافتراضية تحت قيود QoS', description: 'تطوير نموذج برمجة عددية مختلطة تحت قيود QoS وSLA، وتقييم سيناريوهات طلب مرتفع ومتوازن وغير منتظم.' },
      { title: 'تخطيط الموارد البشرية واختيار الموظفين', description: 'تصميم وتحليل استبيان من 14 سؤالًا عبر 8 شركات لدراسة الاختيار والتطوير والتعاقب الوظيفي.' },
    ],
    footerKicker: 'لنحوّل البيانات والعمليات إلى نتيجة أوضح',
    footer: 'متاح لفرص الهندسة الصناعية، تخطيط الإنتاج، تحسين العمليات، والتحول الرقمي.',
  },

  en: {
    meta: {
      title: 'Abdelaziz Abuthuraya | Industrial Engineer & Digital Solutions',
      description: 'Industrial Engineer in Jeddah with experience in production planning, process improvement, quality, and practical digital solutions.',
    },
    skip: 'Skip to content',
    navigationLabel: 'Main navigation',
    name: 'Abdelaziz Abuthuraya',
    brandRole: 'Industrial Engineering × Digital Solutions',
    role: 'Industrial engineer building better operations and clearer digital tools.',
    location: 'Jeddah, Saudi Arabia',
    availability: 'Saudi resident • Valid residency • Open to relocation',
    eyebrow: 'Production planning • Process improvement • Digital transformation',
    intro: 'I combine hands-on manufacturing experience, analytical thinking, and web development to turn operational challenges into practical, usable solutions.',
    contact: 'Contact me',
    download: 'Download CV',
    cvShort: 'CV',
    downloadHref: '/resumes/Abdelaziz-Abuthuraya-CV-EN.pdf',
    language: 'العربية',
    languageLabel: 'التبديل إلى العربية',
    dashboardLabel: 'Professional profile summary',
    status: 'Open to opportunities',
    dashboardText: 'Where operations, data, and digital experience meet.',
    dashboardItems: ['Production', 'Operations', 'Data', 'Systems'],
    nav: ['Profile', 'Experience', 'Projects', 'Skills', 'Education'],
    navIds: ['about', 'experience', 'projects', 'skills', 'education'],
    sections: { about: 'A multidisciplinary engineering profile', experience: 'Field experience across Saudi Arabia and Türkiye', projects: 'Digital solutions built for real use', skills: 'Engineering and technical capabilities', education: 'Education and academic projects' },
    sectionEyebrows: { about: 'Professional profile', experience: 'Experience', projects: 'Technical projects', skills: 'Toolkit', education: 'Academic foundation' },
    summary: 'Industrial Engineering graduate with manufacturing and EPC internship experience in Türkiye and Saudi Arabia. My background covers production planning, quality control, process improvement, and supply-chain analysis, complemented by practical web development skills in React, TypeScript, Supabase, and Three.js.',
    focus: [
      { title: 'Production planning', text: 'Monitoring daily schedules and aligning workflow priorities with delivery deadlines.' },
      { title: 'Process improvement', text: 'Identifying bottlenecks and waste, then translating data into clear recommendations.' },
      { title: 'Quality and flow', text: 'Practical surface and dimensional checks with an understanding of factory material flow.' },
      { title: 'Digital solutions', text: 'Bilingual interfaces that connect operational data with practical user experiences.' },
    ],
    signals: [{ value: '4', label: 'Field experiences' }, { value: '2', label: 'Countries' }, { value: '3', label: 'Technical projects' }, { value: '3', label: 'Languages' }],
    experience: [
      { role: 'Production Planning Intern', company: 'EDAS Yatak', place: 'Kayseri, Türkiye', date: 'Aug - Oct 2025', bullets: ['Supported the preparation and monitoring of daily production schedules to align production activities with delivery deadlines.', 'Coordinated with different departments to support production workflow and address scheduling delays.', 'Analyzed production performance data to identify bottlenecks and recommend process improvements.'] },
      { role: 'Operations & Process Improvement Intern', company: 'Murat Şahin Orman Ürünleri', place: 'Tokat, Türkiye', date: 'Jan - Jul 2025', bullets: ['Supported plywood and MDF production activities across cutting, pressing, and surface-finishing stages.', 'Monitored production workflow to identify inefficiencies and opportunities for waste reduction and improved material handling.', 'Tracked daily output, packaging, and storage; performed surface and dimensional quality checks; and used SolidWorks for basic engineering support.'] },
      { role: 'Project Management Intern', company: 'Delta CJSC', place: 'Jeddah, Saudi Arabia', date: 'Jul - Aug 2024', bullets: ['Supported daily coordination within the engineering, procurement, and construction (EPC) team and organized project documentation.', 'Maintained Excel-based records and prepared reports to support logistics activities and project scheduling.', 'Participated in team meetings and contributed suggestions for improving workflow efficiency.'] },
      { role: 'Engineering Intern', company: 'Delta CJSC', place: 'Riyadh, Saudi Arabia', date: 'Jul - Aug 2022', bullets: ['Supported coordination across engineering, procurement, and construction activities.', 'Monitored project timelines and tracked key performance indicators to support milestone tracking.', 'Prepared and updated Excel reports to support project scheduling and logistics coordination.'] },
    ],
    projectsIntro: 'Three working prototypes showing how I use software to improve visualization, communication, and data capture.',
    projectCopy: {
      form: { type: '3D product visualization', title: 'FORM — Interactive Door Configurator', description: 'A bilingual configurator for dimensions, finishes, hinge direction, and opening angle, with a live specification summary and exploded component view.' },
      kayan: { type: 'Workflow interface', title: 'Kayan — Clearer Process Automation', description: 'An Arabic/English interface built with React and TypeScript, with a working Supabase/PostgreSQL inquiry form, input validation, and Row Level Security.' },
      eclipse: { type: 'Hospitality web experience', title: 'ECLIPSE — Specialty Coffee Website', description: 'A bilingual TanStack Start experience with guided coffee discovery and a server-validated tasting-interest form integrated with the Resend email API.' },
    },
    visit: 'Live demo',
    source: 'Source code',
    skillGroups: [
      { title: 'Engineering & Operations', items: ['Production planning', 'Process improvement', 'Lean Manufacturing', '5S', 'Quality control', 'Supply chain', 'Mathematical modelling', 'Data analysis'] },
      { title: 'Development & Systems', items: ['React', 'TypeScript', 'JavaScript', 'TanStack Start', 'Supabase', 'PostgreSQL', 'REST APIs', 'Three.js', 'WebGL', 'Git / GitHub', 'Vercel'] },
      { title: 'Tools & Languages', items: ['Microsoft Excel', 'SolidWorks', 'AutoCAD', 'Arabic — Native', 'English — C1', 'Turkish — B1'] },
    ],
    education: { degree: 'BSc in Industrial Engineering', school: 'Üsküdar University', place: 'Istanbul, Türkiye', date: '2020 - 2024', detail: 'Language of instruction: English' },
    academic: [
      { title: 'Integrated Supply Chain & Revenue Analysis', description: 'Analyzed raw-material procurement, production performance, and revenue trends, evaluating 85% machine utilization and waste rates of 0.5-1.5% to identify improvement opportunities.' },
      { title: 'Virtual Machine Placement under QoS Constraints', description: 'Developed a Mixed Integer Programming model under QoS and SLA constraints and evaluated overload, balanced, and irregular demand scenarios.' },
      { title: 'Human Resources Planning & Employee Selection', description: 'Designed and analyzed a 14-question survey across eight companies covering employee selection, development, and succession planning.' },
    ],
    footerKicker: 'Let’s turn operations and data into clearer outcomes',
    footer: 'Open to industrial engineering, production planning, process improvement, and digital transformation opportunities.',
  },
}

export { shared }
